### ISSUE TITLE
bash: syntax error near unexpected token `;'

### ISSUE THREAD

**Issue by CeeJay333** [Zeioth/termux-docker#1]
I tried to launch the ./setup.sh Script. First it looks quite good, however at the end I get a syntax error. I attached a screenshot of my termux Session:

![Screenshot_2023-04-04-10-45-41-11](https://user-images.githubusercontent.com/10548506/229739598-21cc67b7-ead6-4095-89a2-5c7a68f28375.jpg)

Any Idea?

**Comment by Zeioth** [comment]
In that screenshot, the process has finished correctly. 

I think that come from the tool 'expect' the script uses. I'm gonna check it out.
