### ISSUE TITLE
Change IP address

### ISSUE THREAD

**Issue by PraveeshRamroop** [Zeioth/termux-docker#4]
When I change the IP address in the /etc/network/interfaces file, I can then no longer ping 8.8.8.8. Why is that and how can I resolve it?

**Comment by Zeioth** [comment]
You can change your ip in [the answerfile](https://github.com/Zeioth/termux-docker/blob/main/alpine/answerfile).

The DHCP of alpine doesn't work properly, and the original author was thinking in using ubuntu as base instead. But you can manually set the IP you want in the meantime.
