### ISSUE TITLE
fail at step 1

### ISSUE THREAD

**Issue by AltairCardinal** [Zeioth/termux-docker#5]
* Connection #0 to host dl-cdn.alpinelinux.org left intact
spawn rm -f ./qemukey ./qemukey.pub
spawn ssh-keygen -b 2048 -t rsa -N  -f ./qemukey
CANNOT LINK EXECUTABLE "ssh-keygen": library "libcrypto.so.3" not found: needed by main executable
cat: ./qemukey.pub: No such file or directory
    while executing
"exec cat ./qemukey.pub"
    invoked from within
"set qemukey [exec cat ./qemukey.pub]"
    (file "/data/data/com.termux/files/home/alpine/installqemu.expect" line 18)

is it network question?

**Comment by Zeioth** [comment]
It's telling you you don't have libcrypto.so.3 installed. Make sure you have `openssl` installed.
